### ISSUE TITLE
Possibly add multi request handler functionality

### ISSUE THREAD

**Issue by tgpholly** [tgpethan/Revolution#5]
Currently Revolution only allows the use of a single request handler and if more than one request handler is included in the modules then the last one that was loaded will be used.

This shouldn't be the case and either
- All request handlers that are loaded should be used when a request is taken in
- User should be notified that there are multiple request handlers and the server will be closed.

Either one of these options can be done or if you have your own creative solution feel free to suggest it.

**Comment by littlemisssynth** [comment]
I'd say that if each request handler had flags attached to it's requests and a central module were used to detect the flag and then pass the request on to the appropriate module, may solve this problem

**Comment by tgpholly** [comment]
The idea is that the the main file will be the centrepoint of it and everything else stems from it, having one required module (consoleHandler) is bad enough.

**Comment by littlemisssynth** [comment]
logically said module would only have to be loaded in scenarios where multiple request handlers are  loaded

**Comment by tgpholly** [comment]
Fair point actually. Could just be an optional module to enable multihandler functionality.
Still I would prefer it to be integrated into the main framework if possible.

**Comment by littlemisssynth** [comment]
it's an effective temporary solution and could eventually be merged into the main framework in theory.

**Comment by tgpholly** [comment]
All in all I would like to keep existing compatibility with existing modules such as EUS, as a compromise it could be an option in the config file?

**Comment by littlemisssynth** [comment]
that would work quite nicely
it may be worth updating existing modules to add compatibility

**Comment by tgpholly** [comment]
Yeah, could be a case of asking the user if they would like to load in compatibility mode with multirequest disabled. Or just flat out disabling multirequest in the framework from the module.

**Comment by tgpholly** [comment]
Because some can't be updated to handle stuff like this.

**Comment by littlemisssynth** [comment]
that makes sense

**Comment by tgpholly** [comment]
How about, if a module states it doesn't work with multireq then shutdown the server with a message saying so.

**Comment by littlemisssynth** [comment]
that should work

**Comment by tgpholly** [comment]
You know, thinking about it, this is a web server and it's not really needed.
The functionality could be added in a module if someone wished to have it so i'll close this.
